# Generated by Django 5.1.2 on 2024-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_candidate_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Candidate_ID',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='username',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
